### ISSUE TITLE
Automatically bumping patch, minor or major

### ISSUE THREAD

**Issue by abulka** [dmerejkowsky/tbump#107]
Looks like you have to explicitly specify the version number each time you run tbump.

What about having flag which looks up the current version and increments it for you (either a patch, minor and major)? Other bumping tools have this kind of thing.

**Comment by dmerejkowsky** [comment]
This feature has already been discussed and we decided not to implement it. See #73 

Since this comes up often, we should probably add a FAQ or something like this to answer those kind of questions :)

**Comment by ionelmc** [comment]
So what's the reason for not having this? What was wrong with that feature in bumpversion?

**Comment by dmerejkowsky** [comment]
Well, it makes the easy thing very easy (like bumping the "patch" part of a project using semver), but the complex stuff very hard - like going from 3.2.2rc1 to 3.2.3 - see https://github.com/peritus/bumpversion/issues/128 for details.

tbump's approach is to make everything just a tiny bit harder (because you have to write a regex and type the entire version number when buming), but it pays off (in my opinion) because it can support *any* versioning scheme with the same level of complexity.
