### ISSUE TITLE
Allow using different config file

### ISSUE THREAD

**Issue by FlorianLudwig** [dmerejkowsky/tbump#90]
I would like specify a config file like:

```
tbump --config /some/path/config.toml 1.2.3
```

**Comment by dmerejkowsky** [comment]
That sounds reasonable, but I got to ask: why?

**Comment by FlorianLudwig** [comment]
My use case is that I want to generate the config in a script as a temp file.

Mostly, just to not have to have another config file in my projects.

Another way of doing it I thought about was to us `thump` as a library and provide all the config via python but a quick look into the code didn't seem like it would be that easy :]

**Comment by dmerejkowsky** [comment]
OK, fair enough. Feel free to open an other feature request for "using tbump as a library"

**Comment by dmerejkowsky** [comment]
So, funny story: I found a use case ;)

I've started using `tbump` to bump PKGBUILD files (used by Arch Linux packages), and it turns out I can probably use the *same* configuration file regardless of the project, using tbump to build PKGBUILDs that are not maintained by me.

So I'll probably implement this one day or an other.

**Comment by achary** [comment]
I find this feature quite useful to keep the top-level directory of a project tidy and free from tooling-related "clutter".
Here is a PR for it: #99

**Comment by dmerejkowsky** [comment]
Yup. By the way, the use case I had in mind with AUR packages required more changes in tbump, because even if the `file` and `hook` configs are the same, I need a place to store the `current_version`.

**Comment by maciejmatczak** [comment]
So that sounds like caching should be separate from config.

I had same thought when thinking about using bumpversion in my org. N tools, but the same management model - so how to share the config, but cache current version separately?

With a common config, I can think of either a symlink (tool independent) or an include directive in config (don't know how toml plays with it) - but tool would have to be enhanced + that would open doors to some config merging/inheritance (start from base config, but extendable).

**Comment by dmerejkowsky** [comment]
> I had same thought when thinking about using bumpversion in my org. N tools, but the same management model - so how to share the config, but cache current version separately?

I don't know, but maybe you'll find that https://copier.readthedocs.io/en/stable/ is a good solution for this problem.
